name: lucaone_tasks
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.13=haa1d7c7_2
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py39h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.14=h993c535_1
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - antlr4-python3-runtime==4.9.3
      - anykeystore==0.2
      - apex==0.9.10.dev0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.11.1
      - biopython==1.80
      - biotite==0.35.0
      - brotlipy==0.7.0
      - cachetools==5.5.2
      - certifi==2025.7.14
      - cffi==1.17.1
      - chardet==3.0.4
      - charset-normalizer==3.1.0
      - click==8.1.8
      - contextlib2==21.6.0
      - contourpy==1.3.0
      - crc32c==2.7.1
      - cryptacular==1.6.2
      - cycler==0.12.1
      - datasets==2.12.0
      - deepspeed==0.5.9
      - defusedxml==0.7.1
      - dill==0.3.6
      - dm-tree==0.1.8
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - fair-esm==2.0.0
      - filelock==3.18.0
      - fire==0.5.0
      - flatbuffers==25.2.10
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2023.5.0
      - gast==0.4.0
      - gemmi==0.5.8
      - google-auth==2.40.3
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - greenlet==3.2.3
      - grpcio==1.74.0
      - h5py==3.8.0
      - hf-xet==1.1.5
      - hjson==3.1.0
      - huggingface-hub==0.34.2
      - hupper==1.12.1
      - idna==2.10
      - importlib-metadata==8.4.0
      - jinja2==3.1.4
      - joblib==1.5.1
      - keras==2.11.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - lightgbm==3.3.5
      - lightning-utilities==0.15.0
      - markdown==3.8.2
      - markupsafe==3.0.2
      - matplotlib==3.6.3
      - ml-collections==0.1.1
      - mock==5.2.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.3
      - multiprocess==0.70.14
      - networkx==3.0
      - ninja==1.11.1.4
      - numpy==1.24.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - obonet==0.3.1
      - omegaconf==2.3.0
      - openpyxl==3.1.2
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==1.5.3
      - pastedeploy==3.1.0
      - patsy==1.0.1
      - pbkdf2==1.3
      - peft==0.8.2
      - pickle5==0.0.11
      - pillow==9.3.0
      - plaster==1.1.2
      - plaster-pastedeploy==1.0.1
      - propcache==0.3.2
      - protobuf==3.19.6
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pymysql==0.10.1
      - pynvml==11.5.0
      - pyparsing==3.2.3
      - pyramid==2.0.2
      - pyramid-mailer==0.15.1
      - python-dateutil==2.9.0.post0
      - python3-openid==3.2.0
      - pytorch-lightning==2.2.5
      - pytz==2025.2
      - pyyaml==6.0.2
      - rdkit==2023.9.4
      - regex==2024.11.6
      - repoze-sendmail==4.4.1
      - requests==2.24.0
      - requests-oauthlib==2.0.0
      - responses==0.18.0
      - rsa==4.9.1
      - sacremoses==0.0.53
      - safetensors==0.5.3
      - scikit-learn==1.2.1
      - scipy==1.10.1
      - seaborn==0.12.2
      - sentencepiece==0.1.97
      - six==1.16.0
      - soupsieve==2.7
      - sqlalchemy==2.0.41
      - statsmodels==0.14.0
      - subword-nmt==0.3.8
      - sympy==1.13.3
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.5.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - tfrecord==1.14.1
      - threadpoolctl==3.6.0
      - timm==0.9.12
      - tokenizers==0.13.2
      - torchmetrics==1.5.2
      - tqdm==4.64.1
      - transaction==5.0
      - transformers==4.29.0
      - translationstring==1.4
      - triton==2.3.0
      - typing-extensions==4.14.1
      - urllib3==1.25.11
      - velruse==1.1.1
      - venusian==3.1.1
      - webob==1.8.9
      - werkzeug==2.2.2
      - wget==3.2
      - wrapt==1.14.1
      - wtforms==3.2.1
      - wtforms-recaptcha==0.3.2
      - xgboost==1.7.3
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.12.0
      - zope-deprecation==5.1
      - zope-interface==7.2
      - zope-sqlalchemy==3.1
prefix: /home/slab/ishiiayuka/.pyenv/versions/anaconda3-2023.03/envs/lucaone_tasks
